/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_MSG_PB_H_INCLUDED
#define PB_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorData {
    float _co2;
    bool has__co;
    int32_t _co;
} SensorData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorData_init_default                  {0, false, 0}
#define SensorData_init_zero                     {0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorData__co2_tag                      1
#define SensorData__co_tag                       2

/* Struct field encoding specification for nanopb */
#define SensorData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    _co2,              1) \
X(a, STATIC,   OPTIONAL, INT32,    _co,               2)
#define SensorData_CALLBACK NULL
#define SensorData_DEFAULT NULL

extern const pb_msgdesc_t SensorData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorData_fields &SensorData_msg

/* Maximum encoded size of messages (where known) */
#define SensorData_size                          16

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
